# Generated by Django 5.1.2 on 2024-11-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_drink_image_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='seats_available',
        ),
    ]
